# Generated by Django 5.2.7 on 2025-11-04 19:20

import django.db.models.deletion
import viewer.rotation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Unnamed Load", max_length=128)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="viewer.shipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HandlingUnit",
            fields=[
                (
                    "id",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("weight", models.FloatField()),
                ("x_size", models.FloatField()),
                ("y_size", models.FloatField()),
                ("z_size", models.FloatField()),
                ("stop", models.CharField(max_length=3)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="viewer.shipment",
                    ),
                ),
                (
                    "temp_add",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="viewer.simulation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("z", models.FloatField()),
                (
                    "orientation",
                    viewer.rotation.RotationField(
                        default=viewer.rotation.Rotation["XYZ"]
                    ),
                ),
                ("temp_remove", models.BooleanField(default=False)),
                (
                    "hu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="viewer.handlingunit",
                    ),
                ),
                (
                    "sim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="viewer.simulation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hu", "sim"), name="shrodingers_placement"
                    )
                ],
            },
        ),
    ]
