# Generated by Django 5.2.7 on 2025-11-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Configuration', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('orientation', models.CharField(default='XYZ', max_length=10)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='viewer.savedconfiguration')),
                ('handling_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.handlingunit')),
            ],
        ),
    ]
