# Generated by Django 5.2.8 on 2025-11-12 20:58

import viewer.restrictions
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_savedconfiguration_savedplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingunit',
            name='restrictions',
            field=viewer.restrictions.RestrictionField(default=viewer.restrictions.Restriction(0)),
        ),
    ]
