# Generated by Django 5.2.7 on 2025-12-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0003_handlingunit_restrictions"),
    ]

    operations = [
        migrations.AddField(
            model_name="handlingunit",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
