# Generated by Django 5.2.7 on 2025-10-11 20:07

import db.rotation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="HandlingUnit",
            fields=[
                (
                    "id",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("weight", models.FloatField()),
                ("x_size", models.FloatField()),
                ("y_size", models.FloatField()),
                ("z_size", models.FloatField()),
                ("stop", models.CharField(max_length=3)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.shipment"
                    ),
                ),
                (
                    "temp_add",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.simulation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("z", models.FloatField()),
                (
                    "orientation",
                    db.rotation.RotationField(default=db.rotation.Rotation["XYZ"]),
                ),
                ("temp_remove", models.BooleanField(default=False)),
                (
                    "hu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.handlingunit",
                    ),
                ),
                (
                    "sim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.simulation"
                    ),
                ),
            ],
        ),
    ]
