# Generated by Django 5.2.7 on 2025-10-19 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="shipment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.shipment",
            ),
            preserve_default=False,
        ),
    ]
