# Generated by Django 5.2.7 on 2025-10-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='name',
            field=models.CharField(default='Unnamed Load', max_length=128),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
