# Generated by Django 5.2.7 on 2025-10-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_simulation_shipment"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="simplacement",
            constraint=models.UniqueConstraint(
                fields=("hu", "sim"), name="shrodingers_placement"
            ),
        ),
    ]
